server:
  port: 8080


spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    driver-class-name: org.h2.Driver
#    #    url: jdbc:mariadb://localhost:3306/study
#    url: jdbc:h2:mem:testdb;MODE=MYSQL
#    username: sa
#    password:
#  jpa:
#    open-in-view: true
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: false
#        format_sql: true
#        highlight_sql: true
#    generate-ddl: true
logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        type.descriptor: trace
        SQL: debug